### ISSUE TITLE
questions about the ML_decoder

### ISSUE THREAD

**Issue by mcgeedunk** [penghui-yang/L2D#2]
Hi, awesome work. I have a few questions about the ML_decoder.

I noticed that during the initialization, the pre-trained teacher network is loaded from state_dict, and then the fc is discarded and replaced by a randomly initialized ML_decoder, in the following lines. 

https://github.com/penghui-yang/L2D/blob/d305c3d24c46749fe97d4e5d2afd8110f552c133/models/tools.py#L19

Does that mean the ML_decoder part of the teacher network is not pre-trained, since the teacher network is fixed, will it produce random results for distillation?

**Comment by penghui-yang** [comment]
Good question.

If I understand correctly, what you talk about are the following statements in several files in the folder `./models` :

```python
if pretrained:
    net.load_state_dict(torch.load(pretrained_model_path["xxx"]))
```

What we load into the models here are the weights of backbones pretrained on ImageNet by unsupervised learning. Those pretrained weights can be easily downloaded from the Internet, and they can be seen as a special initialization of the untrained backbones. Such techniques are widely used in today's SOTA MLL methods.

The real weights of teacher models are saved and loaded by the following statements in the file `main.py`:

```python
if not cfg.teacher_pretrained:
    # omit the training code for teacher models
    torch.save(model_teacher.state_dict(), "pretrained_models/model_teacher_%s_%s_%d.pth" % (cfg.model_t, cfg.dataset, cfg.img_size))
else:
    model_teacher.load_state_dict(torch.load("pretrained_models/model_teacher_%s_%s_%d.pth" % (cfg.model_t, cfg.dataset, cfg.img_size)))
```

The weights of the module **ml-decoder** are also included when saving and loading the weights of teachers.

Hope that answers your question.

**Comment by mcgeedunk** [comment]
Thanks a lot, that addresses my confusion.
