### ISSUE TITLE
coco 类别名称

### ISSUE THREAD

**Issue by swift1988** [penghui-yang/L2D#4]
dataloader.py 中的 class_name  好像和appendix 的anno 索引对应不上。

**Comment by penghui-yang** [comment]
Sorry, I cannot quite understand what you meant. The annotation file only contains the labels of the coco dataset. It has nothing to do with the class_name list. If you don't mind, could you describe your problem in more detail?

**Comment by swift1988** [comment]
The class_name in the dataloder.py does not match the label index provided in the *_anno.json.

Take COCO_val2014_000000000136.jpg as an example. 

The label list in the val_anno.json is [49, 34]. Then, according to the class_name list provided in the dataloder.py, the classes are ‘orange’ and ‘baseball_bat’.

However, according to the original **.jpg** file, this image contains the class of ‘person’ and ‘giraffe’.

It seems the class order in the class_name list is incorrect.

**Comment by penghui-yang** [comment]
Thank you for pointing this out. After adding a ```class_name.sort()```, you can find that ```class_name[34]=="giraffe"``` and ```class_name[49]=="person"```. I have already fixed this issue. I hope this can solve your problem.

**Comment by swift1988** [comment]
Thanks for you reply. It solves my problem
